### PR TITLE
disallows exponents

### PR DESCRIPTION
**Pull request by kzidane**

### CODE REVIEW

**Comment by dmalan** [comment]
Looks like you need a ! to disallow? Currently seems to require an exponent?

**Comment by kzidane** [comment]
@dmalan the ^ is for matching anything but the provided chars. see https://docs.oracle.com/javase/tutorial/essential/regex/char_classes.html!

**Comment by dmalan** [comment]
Did you test? The current expression just means "if the string has at least
one char that isn't E or e", which isn't what you want!

**Comment by kzidane** [comment]
yes, I did, and indeed it disallows strings with at least one char that is an 'E' or an 'e' while still allowing regular floating-points and disallowing unparsable strings.

current expression means "return true if string has only chars that are not 'E's or 'e's. at least one of them."

**Comment by dmalan** [comment]
Ah, my apologies, I had no idea `String.matches` matches full strings (with an implied `^` and `$`). Doesn't even seem to be documented! Cf. http://stackoverflow.com/a/18525028/5156190.

Just committed https://github.com/cs50/java/commit/9cb916fd15f571c58d25103f9b38b8ddce708c55. How's that look? I took the more verbose approach so that the semantics are "if `s` doesn't match a string containing these chars...".

**Comment by kmesbah** [comment]
@dmalan I don't think this disallows leading and trailing spaces. you may wanna add a `\\s` to the list of disallowed chars.

**Comment by kmesbah** [comment]
P.S. if using Java 8, there is `isFinite` for `Float` and `Double` that may substitute the calls to `isInfinite` and `isNaN`.

**Pull request closed without merging**
